### ISSUE TITLE
Error when refreshing breakpoints

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/cloud-debug-proxy-common#17]
It looks like the expected response from `debuggees.breakpoints.list` is a wait token and a list of breakpoints but breakpoints are not always returned.

```
Error: The debuggees.breakpoints.list response from Stackdriver Debug should have the breakpoints and nextWaitToken properties, but it returned this: { nextWaitToken: '23ad7c904aa665e3' }
    at Wrapper.<anonymous> (/Users/talarico/Source/iantalarico/kubernetes-visual-studio-code/extensions/cloud-debug/node_modules/@google-cloud/debug-proxy-common/build/src/wrapper.js:148:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/talarico/Source/iantalarico/kubernetes-visual-studio-code/extensions/cloud-debug/node_modules/@google-cloud/debug-proxy-common/build/src/wrapper.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by iantalarico** [comment]
I also go this error shortly after.  Not sure if it's related or not:

```
The debuggees.breakpoints.list response from Stackdriver Debug contains an element that is not a pending breakpoint: [ { id: '5737bc6ce0c61-b6b8-4b817',
    location: 
     { path: '/Users/talarico/Desktop/test-project/Controllers/HomeController.cs',
       line: 22,
       column: 1 },
    createTime: '2018-08-15T16:25:37.000Z',
    userEmail: 'vscode@cloud-sharp-test.iam.gserviceaccount.com' } ]
Error: The debuggees.breakpoints.list response from Stackdriver Debug contains an element that is not a pending breakpoint: [ { id: '5737bc6ce0c61-b6b8-4b817',
    location: 
     { path: '/Users/talarico/Desktop/test-project/Controllers/HomeController.cs',
       line: 22,
       column: 1 },
    createTime: '2018-08-15T16:25:37.000Z',
    userEmail: 'vscode@cloud-sharp-test.iam.gserviceaccount.com' } ]
    at Wrapper.<anonymous> (/Users/talarico/Source/iantalarico/kubernetes-visual-studio-code/extensions/cloud-debug/node_modules/@google-cloud/debug-proxy-common/build/src/wrapper.js:157:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/talarico/Source/iantalarico/kubernetes-visual-studio-code/extensions/cloud-debug/node_modules/@google-cloud/debug-proxy-common/build/src/wrapper.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by eyqs** [comment]
Could you upgrade this to v0.2.1 in the cloud-debug package.json and check if the error is still there? It may have been fixed already.

**Comment by iantalarico** [comment]
@eyqs I didn't realize there was a new version.  Fixed the problem! thanks!
